/// <reference types="node" />
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      process.env["DATABASE_URL"] ||
      `postgresql://${process.env["DB_USER"] || "postgres"}:${process.env["DB_PASSWORD"] || "postgres"}@${process.env["DB_HOST"] || "localhost"}:${process.env["DB_PORT"] || "5432"}/${process.env["DB_NAME"] || "oncostage_db"}?schema=public`,
  },
});
